# Generated by Django 5.2.3 on 2025-06-29 19:19

import django.db.models.deletion
import informes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dependencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre dependencia')),
                ('responsable', models.CharField(max_length=200, verbose_name='Nombre del responsable')),
                ('correoresponsable', models.CharField(max_length=200, verbose_name='Correo del responsable')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='entecontrol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre ente de control')),
                ('descripcion', models.CharField(blank=True, max_length=40, null=True, verbose_name='Descripcion ente de control')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='entrega',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha de entrega')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='evidencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre')),
                ('archivo', models.FileField(default=informes.models.obtener_archivo_predeterminado, upload_to='pdfs/', verbose_name='Archivo de evidencia')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='informes.entrega')),
            ],
        ),
        migrations.CreateModel(
            name='informe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del informe')),
                ('normativa', models.FileField(default=informes.models.obtener_archivo_predeterminado, upload_to='pdfs/', verbose_name='Normativa')),
                ('descripcion', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Descripcion del informe')),
                ('fechaentregainicial', models.DateField(blank=True, null=True, verbose_name='Fecha inicial de entrega')),
                ('fechaentregapendiente', models.DateField(blank=True, null=True, verbose_name='Fecha pendiente de entrega')),
                ('periodicidad', models.IntegerField(blank=True, null=True, verbose_name='Periodicidad cantidad')),
                ('periodicidadtipo', models.CharField(choices=[('Dias', 'Días'), ('Meses', 'Meses')], max_length=200, verbose_name='Tipo de periodicidad')),
                ('totalentregas', models.IntegerField(blank=True, default='1000', null=True, verbose_name='Total de entregas')),
                ('alarmas', models.IntegerField(blank=True, null=True, verbose_name='Dias de anticipacion de alarma')),
                ('alarmas2', models.IntegerField(blank=True, null=True, verbose_name='Segunda alarma')),
                ('alarmas3', models.IntegerField(blank=True, null=True, verbose_name='Tercera alarma')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('dependencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='informes.dependencia')),
                ('entecontrol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='informes.entecontrol')),
            ],
        ),
        migrations.AddField(
            model_name='entrega',
            name='informe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='informes.informe'),
        ),
    ]
